{% set name = "mammoth" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mammoth-{{ version }}.tar.gz
  sha256: 7924254ab8f03efe55fadc0fd5f7828db831190eb2679d63cb4372873e71c572

build:
  entry_points:
    - mammoth=mammoth.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - cobble >=0.1.3,<0.2

test:
  imports:
    - mammoth
  commands:
    - pip check
    - mammoth --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/mwilliamson/python-mammoth
  summary: Convert Word documents from docx to simple and clean HTML and Markdown
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
    - johnhany97
